// Initial data for localStorage
const INITIAL_DATA = {
  courses: [
    {
      id: 'course-1',
      title: 'Beginner Diver',
      level: 'Open Water',
      description: 'Perfect for first-time divers. Learn the fundamentals of scuba diving in a safe, controlled environment.',
      duration: '3-4 Days',
      maxDepth: '18m',
      price: '$450',
      includes: ['Theory Sessions', 'Pool Training', 'Open Water Dives', 'PADI Certification'],
    },
    {
      id: 'course-2',
      title: 'Advanced Diver',
      level: 'Advanced Open Water',
      description: 'Enhance your skills with specialty dives including deep diving, navigation, and night diving.',
      duration: '2-3 Days',
      maxDepth: '30m',
      price: '$350',
      includes: ['5 Adventure Dives', 'Deep Dive', 'Navigation Dive', 'PADI Certification'],
    },
    {
      id: 'course-3',
      title: 'Professional Diver',
      level: 'Divemaster',
      description: 'Take the first step in your diving career. Become a certified diving professional.',
      duration: '2-4 Weeks',
      maxDepth: '40m',
      price: '$1,200',
      includes: ['Leadership Training', 'Dive Theory', 'Practical Assessment', 'PADI Certification'],
    },
  ],
  excursions: [
    {
      id: 'excursion-1',
      title: 'Reef Dive Adventure',
      location: 'Gan House Reef',
      duration: '2-3 Hours',
      price: '$75',
      description: 'Explore vibrant coral gardens teeming with tropical fish, octopus, and moray eels.',
      image: 'https://images.unsplash.com/photo-1637308105868-a09e02c74a87?w=600&h=400&fit=crop',
    },
    {
      id: 'excursion-2',
      title: 'Manta Point Experience',
      location: 'Manta Point',
      duration: '3-4 Hours',
      price: '$120',
      description: 'Swim alongside majestic manta rays at their famous cleaning station.',
      image: 'https://images.unsplash.com/photo-1623468020653-b0682380e56b?w=600&h=400&fit=crop',
    },
    {
      id: 'excursion-3',
      title: 'Night Dive Expedition',
      location: 'Maradhoo Reef',
      duration: '2 Hours',
      price: '$90',
      description: 'Witness the reef come alive at night with bioluminescent creatures and nocturnal hunters.',
      image: 'https://images.unsplash.com/photo-1682919266273-ce10dbeece41?w=600&h=400&fit=crop',
    },
    {
      id: 'excursion-4',
      title: 'Wreck Diving',
      location: 'British Loyalty Wreck',
      duration: '3-4 Hours',
      price: '$110',
      description: 'Explore the historic WWII tanker wreck, home to schools of barracuda and lionfish.',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop',
    },
    {
      id: 'excursion-5',
      title: 'Shark Point Safari',
      location: 'Shark Point',
      duration: '3 Hours',
      price: '$100',
      description: 'Encounter grey reef sharks, nurse sharks, and other pelagic species in their natural habitat.',
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&h=400&fit=crop',
    },
    {
      id: 'excursion-6',
      title: 'Turtle Sanctuary Dive',
      location: 'Turtle Beach',
      duration: '2-3 Hours',
      price: '$85',
      description: 'Dive with green and hawksbill turtles in their protected feeding grounds.',
      image: 'https://images.unsplash.com/photo-1586281139831-ad877c2d3ff7?w=600&h=400&fit=crop',
    },
  ],
  packages: [
    {
      id: 'package-1',
      name: 'Beginner Package',
      price: '$599',
      popular: false,
      description: 'Perfect for first-time divers',
      features: ['Open Water Course', '4 Guided Dives', 'Equipment Rental', 'Underwater Photos', 'PADI Certification'],
    },
    {
      id: 'package-2',
      name: 'Adventure Package',
      price: '$899',
      popular: true,
      description: 'Most popular choice',
      features: ['Advanced Course', '8 Guided Dives', 'Equipment Rental', 'Underwater Photos & Videos', 'Night Dive Experience', 'Manta Point Visit', 'PADI Certification'],
    },
    {
      id: 'package-3',
      name: 'Pro Package',
      price: '$1,499',
      popular: false,
      description: 'For serious divers',
      features: ['Divemaster Course', '15 Guided Dives', 'Premium Equipment', 'Professional Photo Package', 'All Specialty Dives', 'Wreck & Night Dives', 'Marine Conservation Workshop', 'PADI Certification'],
    },
  ],
  gallery: [
    { id: 'gallery-1', type: 'photo', alt: 'Underwater coral reef', url: 'https://images.unsplash.com/photo-1637308105868-a09e02c74a87?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-2', type: 'photo', alt: 'Diver with sea turtle', url: 'https://images.unsplash.com/photo-1586281139831-ad877c2d3ff7?w=600&h=400&fit=crop', category: 'sea turtles' },
    { id: 'gallery-3', type: 'photo', alt: 'School of tropical fish', url: 'https://images.unsplash.com/photo-1701691796571-48cf3e302b57?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-4', type: 'photo', alt: 'Manta ray closeup', url: 'https://images.unsplash.com/photo-1623468020653-b0682380e56b?w=600&h=400&fit=crop', category: 'manta rays' },
    { id: 'gallery-5', type: 'photo', alt: 'Diving group underwater', url: 'https://images.unsplash.com/photo-1699435558233-baf4214e7432?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-6', type: 'photo', alt: 'Colorful marine life', url: 'https://images.unsplash.com/photo-1701968145515-1202e898baaa?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-7', type: 'photo', alt: 'Sunset boat dive', url: 'https://images.unsplash.com/photo-1697635884187-ea419ad6912f?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-8', type: 'photo', alt: 'Night dive bioluminescence', url: 'https://images.unsplash.com/photo-1682919266273-ce10dbeece41?w=600&h=400&fit=crop', category: 'coral gardens' },
    { id: 'gallery-9', type: 'video', alt: 'Underwater dive video', url: 'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4', category: 'coral gardens' },
    { id: 'gallery-10', type: 'video', alt: 'Manta ray encounter', url: 'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4', category: 'manta rays' },
  ],
  reviews: [
    {
      id: 'review-1',
      name: 'Sarah Johnson',
      country: 'United States',
      rating: 5,
      text: 'Absolutely incredible experience! The instructors were professional, patient, and made me feel safe throughout.',
      course: 'Open Water Course',
    },
    {
      id: 'review-2',
      name: 'Marco Rossi',
      country: 'Italy',
      rating: 5,
      text: 'Best diving center in the Maldives! The equipment was top-notch, and seeing manta rays up close was a dream come true.',
      course: 'Advanced Course',
    },
    {
      id: 'review-3',
      name: 'Yuki Tanaka',
      country: 'Japan',
      rating: 5,
      text: 'Professional team, beautiful dive sites, and excellent organization. The night dive was magical!',
      course: 'Night Dive Experience',
    },
  ],
  team: [
    { id: 'team-1', name: 'Ahmed "Sharky" Rasheed', role: 'Lead Instructor', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d' },
    { id: 'team-2', name: 'Elena Costa', role: 'Marine Biologist', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80' },
    { id: 'team-3', name: 'Mike Williams', role: 'Divemaster', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e' },
  ],
  services: [
    { id: 'service-1', name: 'Beginner Courses', description: 'Start your journey' },
    { id: 'service-2', name: 'Advanced Training', description: 'Level up skills' },
    { id: 'service-3', name: 'Professional Certification', description: 'Go pro' },
    { id: 'service-4', name: 'Equipment Rental', description: 'Top gear' },
    { id: 'service-5', name: 'Guided Dives', description: 'Explore safely' },
  ],
};

export const initializeData = () => {
  Object.keys(INITIAL_DATA).forEach(key => {
    localStorage.setItem(key, JSON.stringify(INITIAL_DATA[key]));
  });
};

export { INITIAL_DATA };